[package]
name = "ethereum-rust-implementation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers-core = "2.0.14"
serde = { version = "1.0.197", features = ["derive"] }
